### ISSUE TITLE
What am i doing wrong ?

### ISSUE THREAD

**Issue by Tuhinshubhra** [theseal/facebook-chat-auto-responder#1]
Every time i get a message the responder fails to send reply and this is the error it shows

ERR! Error in getUserInfo   errorSummary: 'Sorry, something went wrong',
ERR! Error in getUserInfo   errorDescription: 'Please try closing and re-opening your browser window.',
ERR! Error in getUserInfo   payload: null,

What is possibly wrong ?

**Comment by theseal** [comment]
Don't think you are doing something wrong, could be something with the facebook-chat-api library, try to bump it to the lastest release.
